### PR TITLE
Quiet pytest warnings relating to certain classes.

### PR DESCRIPTION
**Pull request by prescod**
Pytest infers that any class with a name starting with the word Test must be a test-case. This checkin quiets warnings relating to certain classes.

Another option would be to disable all classname-based discovery and rely on subclass discovery only.

The pros/cons of that are documented here:

https://stackoverflow.com/a/43349055/11151197

Black also did its thing on some lines.

### CODE REVIEW

**Comment by jstvz** [comment]
Would one of the other answers work? Specifically:

```ini
[pytest]
python_files=test_*.py
```

...did the trick for me.

**Comment by prescod** [comment]
> python_files=test_*.py

Seems totally reasonable and I was hoping to replace my checkin with a one-liner.

But I think it loads files and then looks through the entire Python objectspace whether the classes come from the loaded files or not. It is still picking up TestClass and TestMethod classes. I'm loading them because I'm testing them.

**Comment by davisagli** [comment]
What are the warnings? My output is clean without these changes:
```
(metaci-py3) (pytest|✔) % pytest                                                                                                                           
========================================================================== test session starts ==========================================================================
platform darwin -- Python 3.6.5, pytest-4.3.0, py-1.7.0, pluggy-0.8.1
Django settings: config.settings.test (from ini file)
rootdir: /Users/dglick/Work/MetaCI, inifile: pytest.ini
plugins: tap-2.3, django-3.4.5, django-test-plus-1.1.1
collected 25 items                                                                                                                                                      

metaci/api/tests.py ..                                                                                                                                            [  8%]
metaci/plan/tests/test_handlers.py ..                                                                                                                             [ 16%]
metaci/plan/tests/test_models.py ......                                                                                                                           [ 40%]
metaci/users/tests/test_admin.py ..                                                                                                                               [ 48%]
metaci/users/tests/test_models.py ..                                                                                                                              [ 56%]
metaci/users/tests/test_urls.py ........                                                                                                                          [ 88%]
metaci/users/tests/test_views.py ...                                                                                                                              [100%]

======================================================================= 25 passed in 6.15 seconds =======================================================================
```

**Comment by jstvz** [comment]
I'm confused, sorry. Is the problem that these classes are being discovered? If so, adding the underscore to `pytest.ini` works for me:

```
 λ pytest
======================================== test session starts =========================================
platform darwin -- Python 3.6.8, pytest-4.3.0, py-1.8.0, pluggy-0.9.0
Django settings: config.settings.test (from ini file)
rootdir: /Users/jestevez/projects/rel/MetaCI, inifile: pytest.ini
plugins: django-3.4.8, django-test-plus-1.1.1
collected 23 items

metaci/plan/tests/test_handlers.py ..                                                          [  8%]
metaci/plan/tests/test_models.py ......                                                        [ 34%]
metaci/users/tests/test_admin.py ..                                                            [ 43%]
metaci/users/tests/test_models.py ..                                                           [ 52%]
metaci/users/tests/test_urls.py ........                                                       [ 86%]
metaci/users/tests/test_views.py ...                                                           [100%]

===================================== 23 passed in 6.71 seconds ======================================
```

**Comment by prescod** [comment]
Everybody else's output is clean without the warnings because nobody else is running code that imports those classes. But I have a branch with code that generates the warnings.

Why don't we hold this pull request until the other one is merged and then everyone can see it and we can experiment with techniques to fix it.

I'll just put up with the warnings for now.

**Comment by jstvz** [comment]
Ah, now I get it. Thanks for the clarification.

**Comment by davisagli** [comment]
I think we'll probably want to figure out how to restrict pytest to looking in tests directories, but it'll be easiest to do once we can reproduce the warnings.

**Comment by prescod** [comment]
Okay now everyone should see the warnings on master.

If you have a node_modules directory you might also get an error which is fixed by adding this line to pytest.ini:

norecursedirs = node_modules dist src

https://www.reddit.com/r/ProgrammerHumor/comments/6s0wov/heaviest_objects_in_the_universe/

**Comment by davisagli** [comment]
I just tested on master. The combination of `python_files=test_*.py` and `norecursedirs = node_modules dist src` appears to avoid the warnings, so I'd like to go with that rather than these markers on specific tests.

**Pull request closed without merging**
